name: Deploy Flutter Web to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.2'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web for root domain
        run: flutter build web --release --base-href /

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-web-build
          path: build/web

